<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleconfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleconfiguracionRepository extends EntityRepository
{
}