<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DirectivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectivoRepository extends EntityRepository
{
}