<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JurisdiccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JurisdiccionRepository extends EntityRepository
{
}