<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PresentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentacionRepository extends EntityRepository
{
}