<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariovotanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariovotanteRepository extends EntityRepository
{
}