<?php
namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViaticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViaticoRepository extends EntityRepository
{
}